export enum ChatIntent {
  CAMPAIGN_CREATION = 'CAMPAIGN_CREATION',
  REPORT_QUERY = 'REPORT_QUERY',
  KPI_ANALYSIS = 'KPI_ANALYSIS',
  PIXEL_SETUP = 'PIXEL_SETUP',
  BUDGET_OPTIMIZATION = 'BUDGET_OPTIMIZATION',
  GENERAL = 'GENERAL',
}
