export enum ChatIntent {
  CAMPAIGN_CREATION = 'CAMPAIGN_CREATION',
  REPORT_QUERY = 'REPORT_QUERY',
  KPI_ANALYSIS = 'KPI_ANALYSIS',
  PIXEL_SETUP = 'PIXEL_SETUP',
  BUDGET_OPTIMIZATION = 'BUDGET_OPTIMIZATION',
  // 2026 Meta Trinity 기반 신규 인텐트
  CREATIVE_FATIGUE = 'CREATIVE_FATIGUE',
  LEARNING_PHASE = 'LEARNING_PHASE',
  STRUCTURE_OPTIMIZATION = 'STRUCTURE_OPTIMIZATION',
  LEAD_QUALITY = 'LEAD_QUALITY',
  TRACKING_HEALTH = 'TRACKING_HEALTH',
  GENERAL = 'GENERAL',
}
