export { Money, type Currency } from './Money'
export { DateRange } from './DateRange'
export { Percentage, type PercentageOptions } from './Percentage'
export {
  CampaignStatus,
  CAMPAIGN_STATUS_TRANSITIONS,
  canTransition,
  isEditableStatus,
  isActiveStatus,
  isTerminalStatus,
} from './CampaignStatus'
export {
  CampaignObjective,
  CAMPAIGN_OBJECTIVE_LABELS,
  CAMPAIGN_OBJECTIVE_DESCRIPTIONS,
} from './CampaignObjective'
// Admin-related value objects
export {
  GlobalRole,
  GLOBAL_ROLE_PERMISSIONS,
  ROLE_HIERARCHY,
  type GlobalRolePermissions,
  isAdmin,
  isSuperAdmin,
  canAccessAdminPanel,
  canManageUsers,
  canManageAdmins,
  canProcessRefunds,
  canViewPayments,
  getRoleLabel,
  getRoleDescription,
  getAllGlobalRoles,
  hasHigherOrEqualRole,
  canManageRole,
} from './GlobalRole'
export {
  SubscriptionPlan,
  PLAN_CONFIGS,
  PLAN_HIERARCHY as SUBSCRIPTION_PLAN_HIERARCHY,
  type PlanConfig,
  getPlanConfig,
  getPlanLabel,
  getPlanPrice,
  getPlanFeatures,
  isFreePlan,
  isPaidPlan,
  getAllPlans,
  getPaidPlans,
  canUpgradeTo,
} from './SubscriptionPlan'
export {
  SubscriptionStatus,
  SUBSCRIPTION_STATUS_TRANSITIONS,
  canTransitionSubscription,
  isActiveSubscription,
  isCancelledSubscription,
  isTrialingSubscription,
  isPastDue,
  getStatusLabel as getSubscriptionStatusLabel,
  getStatusDescription as getSubscriptionStatusDescription,
  getAllSubscriptionStatuses,
} from './SubscriptionStatus'
export {
  InvoiceStatus,
  INVOICE_STATUS_TRANSITIONS,
  canTransitionInvoice,
  isPendingInvoice,
  isPaidInvoice,
  isFailedInvoice,
  isRefundedInvoice,
  isPartiallyRefunded,
  canBeRefunded,
  getStatusLabel as getInvoiceStatusLabel,
  getStatusDescription as getInvoiceStatusDescription,
  getStatusColor as getInvoiceStatusColor,
  getAllInvoiceStatuses,
} from './InvoiceStatus'
export {
  // Types
  type Industry,
  type BusinessScale,
  type AOVTier,
  type BudgetRecommendationSource,
  type AOVSource,
  // Interfaces
  type IndustryBudgetBenchmark,
  type BusinessScaleMultiplier,
  type AOVTierConfig,
  type BudgetRange,
  type BudgetRecommendationInput,
  type ExistingCampaignData,
  type BudgetRecommendation,
  // Constants
  MINIMUM_DAILY_BUDGET,
  DEFAULT_MARGIN_RATE,
  TEST_PERIOD_DAYS,
  INDUSTRY_BUDGET_BENCHMARKS,
  BUSINESS_SCALE_MULTIPLIERS,
  AOV_TIER_CONFIGS,
  MONTHLY_BUDGET_RATIOS,
  // Functions
  getAOVTier,
  calculateTargetROAS,
  calculateDailyBudgetFromMonthly,
  calculateBudgetRange,
  calculateTestBudget,
  calculateTargetCPA,
  getIndustryLabel,
  getBusinessScaleLabel,
  getAOVTierLabel,
  getAllIndustries,
  getAllBusinessScales,
  formatBudget,
  formatROAS,
} from './BudgetRecommendation'
