// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Use DATABASE_URL by default, use DATABASE_URL_TEST only when NODE_ENV=test
const isTestEnv = process.env["NODE_ENV"] === "test";
const databaseUrl = isTestEnv
  ? (process.env["DATABASE_URL_TEST"] || process.env["DATABASE_URL"])
  : process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
